### ISSUE TITLE
MIDI noteOFF doesn't run

### ISSUE THREAD

**Issue by TitoPalacios** [t-bre/MIDIAnalyser#12] opened 2020-04-05 10:48 UTC
HI, first all great job!!
When I connect my piano (KAWAi) using midi bluetooth connection it's like doesn't receives Note OFF event. All the keys in appears on green and never returns to white (off position).This not happen using virtual midi piano on my iPad.

**Comment by t-bre** [comment] 2020-04-05 11:04
Thanks for the feedback, it is great to have information on how the app runs on devices other than my own. This is a known issue but I am having trouble solving it as it doesn't happen on my Mac. I have seen it happen before on another laptop running an older version of macOS so it would be good to know which Mac hardware you have and which version of macOS you are running? 

I am planning a rewrite of most of the app soon which will possibly solve this issue if it is related to how noteOff events are handled.

**Comment by TitoPalacios** [comment] 2020-04-06 07:37
Hi,
my laptop is MacBook Pro 2017 ed. and macOS Catalina Version 10.15.4.

**Comment by TitoPalacios** [comment] 2020-04-11 19:44
I have been debugging the code and using my piano with the AudioKit's MIDI Utility and the results are the same. Never receives NoteOFF event. Surfing on internet I found this link with information about the problem and possible solution (https://github.com/AudioKit/AudioKit/issues/1832) => Problems with 88 keys keyboards and the MIDI listener protocol.
I hope it's help you.

**Comment by t-bre** [comment] 2020-04-11 19:56
Thanks for the update - I believe the issue is most likely with the AudioKit framework itself not triggering noteOff events for some MIDI keyboards which then leads to the stuck keys. The next version of the app will be updated with a newer version of AudioKit which I hope will resolve this issue. If not I will have a look at if there is any additional software / driver which can be installed to help with AudioKit compatibility.

**Comment by t-bre** [comment] 2020-07-03 16:11
@TitoPalacios I believe I have fixed this issue by downgrading AudioKit to version 4.5.6. If you could test the latest beta for me on your device that would be much appreciated:  [MIDIAnalyser 2.0.0 Beta 2](https://github.com/t-bre/MIDIAnalyser/releases/tag/2.0.0-beta-2).

**Comment by TitoPalacios** [comment] 2020-07-12 09:33
Hi @t-bre, I confirm that the dmg version works using the bluetooth MIDI keyboard. I'm using the Kawai ES110 piano keyboard. I'll be looking forward to the version you release soon. If you prefer I can close the issue or leave it open waiting for you to release the final version. Great work.

**Comment by t-bre** [comment] 2020-07-12 10:42
I will close this issue when I release version 2.0.0 sometime in the next month. Thanks for your help, much appreciated.

**Closed** 2020-10-05 19:55 UTC
